AWSTemplateFormatVersion: "2010-09-09"
Description: Backend ECS Service running on AWS Fargate (Port 9000)

Resources:
  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: flask-backend
      Cluster: !ImportValue ecs-cluster-name
      TaskDefinition: !ImportValue backend-task-definition-arn
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue flask-express-PublicSubnet1
            - !ImportValue flask-express-PublicSubnet2
          SecurityGroups:
            - !ImportValue flask-express-BackendSG

Outputs:
  BackendServiceName:
    Description: Backend ECS Service Name
    Value: !Ref BackendService
