AWSTemplateFormatVersion: "2010-09-09"

Description: ECS Cluster for Flask backend and Express frontend

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: flask-express-cluster

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: ecs-cluster-name
