AWSTemplateFormatVersion: "2010-09-09"
Description: Frontend ECS Service running on AWS Fargate (Port 8000)

Resources:
  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: express-frontend-service
      Cluster: !ImportValue ecs-cluster-name
      TaskDefinition: !ImportValue frontend-task-definition-arn
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !ImportValue ecs-public-subnet-1
            - !ImportValue ecs-public-subnet-2
          SecurityGroups:
            - !ImportValue express-frontend-sg-id

Outputs:
  FrontendServiceName:
    Description: Frontend ECS Service Name
    Value: !Ref FrontendService
